### ISSUE TITLE
Update to Django 2.2 LTS

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#485] opened 2019-04-18 15:21 UTC
Django 2.2 LTS [has just been released](https://www.djangoproject.com/download/). We should update to this version over the summer.

All other django-* libraries in the requirements should also be tested and updated as we move to this new version

**Comment by jonespm** [comment] 2019-08-14 14:26
@ssciolla was talking about this so I'm assigning to him to also look at what this would take.

**Comment by ssciolla** [comment] 2019-10-23 21:03
I made some good progress on this today and worked with @jonespm to debug a couple issues. With the latest commits in my [issue branch here](https://github.com/ssciolla/my-learning-analytics/commits/issue-485-django-update), I was able to get the application to run (and collect data via the cron) using Python 3.7 and Django 2.2.6. We'll need to do more testing to make sure all the dependencies are still working as expected and that this also works in OpenShift, but hopefully I'll have a PR soon.

**Comment by ssciolla** [comment] 2019-10-24 13:46
It's looking like issue #484 would also be addressed by my work on this.

**Comment by ssciolla** [comment] 2019-10-24 18:20
@jonespm, speaking of SAML, I'm going to deploy this to test, and I'm pretty sure I'll find that the djangosaml2 library we're using will break, since it doesn't appear to support Django 2.2 (it doesn't appear to have been rewritten using Django 2 at least).

If or when that happens, we'll need to have an exit strategy for this dependency and a replacement. [`social-app-django`](https://github.com/python-social-auth/social-app-django) seems to be alternative, but perhaps you've already done a survey of what's out there? Thoughts?

**Comment by ssciolla** [comment] 2019-10-24 19:20
Update: I deployed to the test instance, and it didn't seem to break the SAML authentication. I was seeing a couple tracebacks (I think related to the Django Debug Toolbar and Watchman?). I'll need to do some more testing; it still seems like it might be a good idea to move away from `djangosaml2`.

**Comment by jonespm** [comment] 2019-10-24 19:30
I haven't really looked at anything else. For next year I'd probably prefer
just to be using LTI instead rather than the SAML integration. This was
just more convenient for us to setup at the time. It's also possible the
LTI module will need to switch as this is the only 1.3 library I can find.

https://pypi.org/project/PyLTI1p3/

**Comment by ssciolla** [comment] 2019-10-24 19:32
Hm... okay, but that would only solve MyLA; we may need to solve this problem for Student Explorer.

**Comment by jonespm** [comment] 2019-10-24 19:33
Student Explorer is on holiday after this release. ;) 🍹

**Comment by jonespm** [comment] 2019-10-24 19:34
Yeah, if it doesn't work we'll have to look at something else. This library wasn't my choice it was just already being used.

**Closed** 2020-01-15 14:35 UTC

**Comment by pushyamig** [comment] 2020-02-04 18:42
Test Case should be written mentioning what all the libraries that got updated based on the Django 2.2 making it easier for testing
Currently, `Pip Freeze` gives me this, But i am not sure if those are compatible version for Django 2.2. I am assuming since application functioning as it supposed( via regression testing) to then we can confirm upgrade successful
```
Django==2.2.9
django-common-helpers==0.9.2
django-cron==0.5.1
django-csp==3.5
django-debug-toolbar==2.0
django-jsonview==1.3.1
django-lti-auth==1.0.0
django-macros==0.4.0
django-model-utils==3.2.0
django-npm==1.0.0
django-ptvsd-debug==1.0.3
django-registration==3.0.1
django-settings-export==1.2.1
django-su==0.8.0
django-watchman==0.18.0
django-webpack-loader==0.6.0
djangosaml2==0.17.2
```

**Comment by pushyamig** [comment] 2020-02-05 13:53
All the versions look Good.
@jennlove-um if your regression testing the app feel good then we can resolve this issue

**Comment by jennlove-um** [comment] 2020-02-05 19:40
@pushyamig So far in testing, I have not found any problems.

**Comment by zqian** [comment] 2020-02-05 20:01
Verified from OpenShift build log file:

Collecting Django<2.2.9.99,>=2.2.9
Downloading Django-2.2.9-py3-none-any.whl (7.5 MB)
