### ISSUE TITLE
Create a data dictionary that details the information captured in the logs about student use of the visualization pages

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#340] opened 2019-01-07 19:25 UTC
Create a data dictionary that details the information captured in the logs about student use of the visualization pages

**Comment by jennlove-um** [comment] 2019-01-17 18:42
What is the status of this? 
Also, is this the same as #341?

**Comment by pushyamig** [comment] 2019-01-17 20:08
I have the data dump from requests table, MyLA(eventlog_log, user) tables of Fall pilot courses in this [folder](https://drive.google.com/drive/u/0/folders/1SgVV12A7_3JLevO7ehShB-4YYN37UeKz). the `eventlog_log` table is where all user actions, meaning what visualization they have viewed and all that. Google analytics is another piece where you have user log data. is that also needed?

**Comment by jennlove-um** [comment] 2019-01-24 21:38
this is a duplicate of #341.  I've copied Pushyami's comment over there so everything is in one issue.

**Closed** 2019-01-24 21:37 UTC
