### ISSUE TITLE
Upgrade to promise 2.3.2 package crashing the Assignment redesign view

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#994] opened 2020-07-23 20:19 UTC
During the docker build we see this error message
1. `ERROR: graphql-core 2.3.2 has requirement promise<3,>=2.3, but you'll have promise 2.2.1 which is incompatible.`
2. `requirements.txt` has a [comment](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/requirements.txt#L16) stating this for promise package `# Force this version of promise because the newest version doesn't support dict`
3. After Upgrading to promise 2.3.2 when trying to open the assignment redesign view crashes and present with pretty message "Something went wrong". Below is the stack trace 
```
[2020-07-23 16:12:20 -0400] [ERROR] [utils.py:155] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/promise/promise.py", line 489, in _resolve_from_executor
  executor(resolve, reject)
 File "/usr/local/lib/python3.8/site-packages/promise/promise.py", line 756, in executor
  return resolve(f(*args, **kwargs))
File "/usr/local/lib/python3.8/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
  return next(*args, **kwargs)
 File "/code/dashboard/graphql/objects.py", line 114, in resolve_current_user_submission
  return info.context.submission_by_assignment_id_and_user_id_loader.load({
File "/usr/local/lib/python3.8/site-packages/promise/dataloader.py", line 97, in load
    cached_promise = self._promise_cache.get(cache_key)
graphql.error.located_error.GraphQLLocatedError: unhashable type: 'dict' 
```

This seems to be know issue as stated in the requirements.txt so downgraded the package to `2.2.1`. 
I am not sure if this support ever going to be there or we need to change the design of the Backend for fetching the required data

@andrew-gardener Thoughts????

**Comment by andrew-gardener** [comment] 2020-07-24 17:07
@pushyamig sorry I can't look into this too deeply right now (working on something time sensitive). If `graphene-django` and `promise` both need to be updated then probably all the `DataLoader` classes in `loaders.py` need to be updated. If its a huge problem they can be removed completely (replaced with inline queries) but it might cause the graphql queries to run much slower depending on the query structure.

**Comment by pushyamig** [comment] 2020-07-24 18:54
@andrew-gardener, I am upgrading myla with Django 3 as part of that I upgraded to
`graphene-django==2.12.1` from graphene-django==2.8
To me the below error occurred even with the `graphene-django==2.8` version. 
`ERROR: graphql-core 2.3.2 has requirement promise<3,>=2.3, but you'll have promise 2.2.1 which is incompatible.` 
I looked up the installation guide for the [Graphene-django](https://docs.graphene-python.org/projects/django/en/latest/installation/) it stay the version of django it supports is > 1.11 and did not mention anything about djangov3

The stack trace occurred with `promise 2.3` and  `graphene-django==2.12.1` so i revered back promise to 2.2.1 ( as you chose before) that went away. 

To me after upgrade to `graphene-django==2.12.1` I was able to fetch assignment data and set data ( that tells me mutations was fine as well)

I did not see the feel the need `promise` need to updated but with updated `graphene-django` things seems to be ok. 

Can you recall why they didn't support the dict in promise with later versions? I looked up the their github issues I did not see any mention as such.

I don't know much about this GraphQL code so I am trying to ask you

**Comment by andrew-gardener** [comment] 2020-07-24 20:04
If using the slightly older version of `graphene-django` works with django v3 upgrades, then I think you should stick with that for now and I'll try and see what I can do about updating `graphene-django` (and promise) to latest once I have a bit more free time. I think I just need to rewrite how the dataloaders take input (like maybe make my own hashable dict object and pass it in instead of dict directly)

**Comment by pushyamig** [comment] 2020-07-24 20:13
@andrew-gardener I will stick with the version you chose for both `graphene-django==2.8` and `promise==2.2.1` for Django 3.

When you get to a point you can you can make the change, assign the issue to yourself. Thanks for taking a look

**Comment by andrew-gardener** [comment] 2020-07-24 20:18
I'll assign it to myself now. I might be able to get to it within 2 weeks

**Comment by andrew-gardener** [comment] 2020-07-29 18:32
@pushyamig was able to fix it in #997 (needed to look at the promise lib source code to see what was happening). Turns out it was just that the way `get_cache_key` changed (semi-drastically) and examples/docs in other places wasn't really updated to reflect.

**Closed** 2020-08-18 12:09 UTC

**Comment by ssciolla** [comment] 2020-08-24 17:55
I will QA.

**Comment by ssciolla** [comment] 2020-08-25 17:03
I confirmed that the new dependencies and changes have been incorporated, and the Assignment Re-Design is still pulling and updating data from/in the database successfully. Moving to Done.
