### ISSUE TITLE
When adding a new course, need to update resource_access from the beginning of the term

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1006] opened 2020-08-05 18:53 UTC
If a course is added part way through the semester (even a few days/week later) it's events will only populate from the time it's added.

To fix this I believe we'll have to make the job 

- [x] Check if there are any courses newly added since the last run

- [x] If there are, run the update from the start of the term for the new courses

- [x] Add a new column to the courses table to indicate when the data was last refreshed for that course

The way Bigquery works it doesn't matter if you run it for select courses or all courses, it's the same cost currently, so we'll just have to remove all of the events since the start of this new courses term and update them.

I believe checking if there are new courses might be useful for other reasons (like if we wanted the cron to run more frequently). For instance we *could* run the cron hourly but only if there's new courses, otherwise we'd just do the daily run.

_Originally posted by @jonespm in https://github.com/tl-its-umich-edu/my-learning-analytics/issues/973#issuecomment-669401541_

**Comment by ssciolla** [comment] 2020-08-05 18:57
Hm, yeah, I think we need to address this. We can't assume all the courses will be added at the beginning of the term.

**Comment by jennlove-um** [comment] 2020-08-05 19:41
Agreed - this makes sense to address

**Comment by jonespm** [comment] 2020-08-06 15:41
So I'm thinking about the first question.

You can tell that the course is *new* if there is a course but no users yet loaded for the course. How can we do this with Django ORM or SQL?

If either of these return rows there's new courses to process:
`SELECT id FROM course WHERE id NOT IN (SELECT course_id FROM user);`

This would be the same as this join:
`SELECT course.id FROM course LEFT JOIN USER ON USER.course_id = course.id WHERE USER.id IS NULL;`

Maybe just use one of those queries rather than modifying the schema.

**Comment by ssciolla** [comment] 2020-08-06 16:17
@jonespm, @zqian basically did this with the ORM in this PR:

https://github.com/tl-its-umich-edu/my-learning-analytics/pull/977/files#diff-474394b3595bf5cedbf0bf5ee1080b66R131-R132

Probably not worth abstracting to a utility function or model method; it's a one-liner.

**Comment by jonespm** [comment] 2020-08-06 16:39
That's not exactly the same thing, that is given a course_id and just checks if a specific course has no data. This need to answer the question "Do any courses not have data" 

This would either need to be a for loop around that one-liner or something else.

**Comment by ssciolla** [comment] 2020-08-06 17:01
Doh, yeah, you're right. Not sure we can use the ORM with a single underlying query for this, given that we don't have foreign keys. One of what you listed might work. You could probably do an aggregate (`GROUP BY`) in the second?

**Comment by lsloan** [comment] 2020-08-13 15:12
I think #1012 may be a duplicate of this issue. If it seems the same, let me know and we can close it.

**Closed** 2020-09-14 17:13 UTC
Labels: cron, ⚠️ priority

**Comment by jennlove-um** [comment] 2020-09-15 15:38
Testing passes: The new column is in the table and populates with the last update date.  Resource access events from the beginning of the course are being added when MyLA is turned on several weeks into the course.
